export const CHANNELS = {
	AUTH: {
		LOGIN: "login",
		CHECK_TOKEN: "check-token",
	},
	MICROSOFT: {
		IS_USER_AUTHENTICATED: "is-user-authenticated",
		LOGIN: "login",
		LOGOUT: "logout",
		GET_ONEDRIVE_DOCS: "onedrive docs",
	},
	STORAGE: {
		GET_TOKEN: "get-token",
		SET_TOKEN: "set-token",
		CLEAR_TOKEN: "clear-token",
	},
	CYBER: {
		ADD_CYBER: "add-cyber",
		GET_ALL_CYBER: "get-all-cyber",
		EDIT_CYBER: "edit-cyber",
		DEL_CYBER: "del-cyber",
	},
	APP_CHAMP: {
		APP_CHAMP_ADD: "appChamp-add",
		APP_CHAMP_GET_ALL: "appChamp-get-all",
		APP_CHAMP_GET_SHORT: "appChamp-get-short",
		APP_CHAMP_EDIT: "appChamp-edit",
		APP_CHAMP_DEL: "appChamp-del",
	},
	TEAM_NAME: {
		ADD_NAME: "team-name-add",
		GET_ALL_NAMES: "team-name-all-get",
		EDIT_NAME: "team-name-edit",
		DEL_NAME: "team-name-del",
	},
	TEAMS_TRANSFER: {
		SAVE: "teams-transfer-save",
		GET_TEAMS_LIST: "teams-transfer-get-list",
	},
	ANALYZE: {
		ADD_URL: "add-url",
		GET_STATIC_LIST: "get-static-list",
		UPD_TEMP: "update-temp",
		ACTIVE: "active",
		MATCH_CHECK: "match-check",
		CONNECT: "connect",
		SHOW_NOTIFICATION: "show-notification",
		DISCONNECT: "disconnect",
	},
	LINES: {
		GET_LINES: "lines-get",
		GET_LINES_LIST: "lines-get-list",
		DOWNLOAD_LINES: "lines-download",
		DELETE_LINES: "lines-delete",
	},
	PARSER: {
		ADD_URL: "parser-add-url",
		GET_URL: "parser-get-utl-list",
		UPD_URL: "parser-upd-url",
		DELETE_URLS: "parser-delete-all-url",
		ANALYZE: "parser-analyze",
		FILTER_LIST: "filter-list",
		FILTER_ADD_CHAMP: "filter-add-championship",
		FILTER_DELETE_CHAMP: "filter-delete-champ",
	},
	PARCER_DATA: {
		GET_DATA_LIST: "parcer-data-get-list",
		DOWNLOAD: "parcer-data-download",
		DELETE: "parcer-data-delete",
	},
	DIALOG: {
		SAVE_FILE: "dialog-save-file",
	},
	AUTO_UPDATE: {
		AVAILABLE: "update-available",
		DOWNLOAD: "update-downloaded",
		UPDATE: "update-restart",
	},
	BETTING_RESULTS: {
		GET_RESULTS: "betting-get-results",
	},
	MANUAL_ADDING: {
		GET_MANUAL_LIST: "manual-list-get",
		SAVE_MANUAL_LIST: "manual-list-save",
		ADD_MANUAL_URL: "manual-url-add",
	},
	SETTINGS: {
		GET_ADDRESS: "settings-get-address",
		SET_ADDRESS: "settings-set-address",
		GET_HALVES_FILES_NAMES: "settings-get-halves-files-names",
		SET_FILES_NAMES: "settings-set-files-names",
		GET_CYBER_FILE_NAME: "settings-get-cyber-file-name",
		SET_CYBER_FILE_NAME: "settings-set-cyber-file-name",
	},
};
